/**
 * signup
 */
export const USER_SIGN_UP_LOADING = "USER_SIGN_UP_LOADING";
export const USER_SIGN_UP = "USER_SIGN_UP";
export const USER_SIGN_UP_ERROR = "USER_SIGN_UP_ERROR";

/**change isAuthenticated state */
export const USER_AUTHORIZED: String = "USER_AUTHORIZED";

/**
 * Login
 */
export const LOGIN_USER_LOADING = "LOGIN_USER_LOADING";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

/**
 * loGOUT
 */

export const LOGOUT_USER = "LOGOUT_USER";

// forgot password

export const PASSWORD_RESET_LOADING = "PASSWORD_RESET_LOADING";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_ERROR = "PASSWORD_RESET_ERROR";

// otp
export const PASSWORD_CHANGE_OTP_LOADING = "PASSWORD_CHANGE_OTP_LOADING";
export const PASSWORD_CHANGE_OTP_SUCCESS = "PASSWORD_CHANGE_OTP_SUCCESS";
export const PASSWORD_CHANGE_OTP_ERROR = "PASSWORD_CHANGE_OTP_ERROR";
