export const GET_ALL_B2B_PRODUCT_LOADING = "GET_ALL_B2B_PRODUCT_LOADING";
export const GET_ALL_B2B_PRODUCT_SUCCESS = "GET_ALL_B2B_PRODUCT_SUCCESS";
export const GET_ALL_B2B_PRODUCT_ERROR = "GET_ALL_B2B_PRODUCT_ERROR";

//detail
export const GET_DETAIL_B2B_PRODUCT_LOADING = "GET_DETAIL_B2B_PRODUCT_LOADING";
export const GET_DETAIL_B2B_PRODUCT_SUCCESS = "GET_DETAIL_B2B_PRODUCT_SUCCESS";
export const GET_DETAIL_B2B_PRODUCT_ERROR = "GET_DETAIL_B2B_PRODUCT_ERROR";

/**
 *  Property
 *
 */

export const GET_ALL_B2B_PROPERTY_LOADING = "GET_ALL_B2B_PROPERTY_LOADING";
export const GET_ALL_B2B_PROPERTY_SUCCESS = "GET_ALL_B2B_PROPERTY_SUCCESS";
export const GET_ALL_B2B_PROPERTY_ERROR = "GET_ALL_B2B_PROPERTY_ERROR";

export const GET_DETAIL_B2B_PROPERTY_LOADING =
  "GET_DETAIL_B2B_PROPERTY_LOADING";
export const GET_DETAIL_B2B_PROPERTY_SUCCESS =
  "GET_DETAIL_B2B_PROPERTY_SUCCESS";
export const GET_DETAIL_B2B_PROPERTY_ERROR = "GET_DETAIL_B2B_PROPERTY_ERROR";
