// post Career
export const CREATE_CAREER_LOADING = "CREATE_CAREER_LOADING";
export const CREATE_CAREER_SUCCESS = "CREATE_CAREER_SUCCESS";
export const CREATE_CAREER_ERROR = "CREATE_CAREER_ERROR";

// post cv
export const POST_CV_LOADING = "POST_CV_LOADING";
export const POST_CV_SUCCESS = "POST_CV_SUCCESS";
export const POST_CV_ERROR = "POST_CV_ERROR";

// post talents
export const POST_TALENT_LOADING = "POST_TALENT_LOADING";
export const POST_TALENT_SUCCESS = "POST_TALENT_SUCCESS";
export const POST_TALENT_ERROR = "POST_TALENT_ERROR";

// getCareerCv
export const GET_CAREER_CV_LOADING = "GET_CAREER_CV_LOADING";
export const GET_CAREER_CV_SUCCESS = "GET_CAREER_CV_SUCCESS";
export const GET_CAREER_CV_ERROR = "GET_CAREER_CV_ERROR";

// getJob
export const GET_JOB_LOADING = "GET_JOB_LOADING";
export const GET_JOB_SUCCESS = "GET_JOB_SUCCESS";
export const GET_JOB_ERROR = "GET_JOB_ERROR";
//getJobPosting
export const GET_JOB_POSTING_LOADING = "GET_JOB_POSTING_LOADING";
export const GET_JOB_POSTING_SUCCESS = "GET_JOB_POSTING_SUCCESS";
export const GET_JOB_POSTING_ERROR = "GET_JOB_POSTING_ERROR";

//get career talent

export const GET_CAREER_TALENT_LOADING = "GET_CAREER_TALENT_LOADING";
export const GET_CAREER_TALENT_SUCCESS = "GET_CAREER_TALENT_SUCCESS";
export const GET_CAREER_TALENT_ERROR = "GET_CAREER_TALENT_ERROR";
