export const GET_ALL_FRIENDS_LOADING = "GET_ALL_FRIENDS_LOADING";
export const GET_ALL_FRIENDS_SUCCESS = "GET_ALL_FRIENDS_SUCCESS";
export const GET_ALL_FRIENDS_ERROR = "GET_ALL_FRIENDS_ERROR";

/**
 * GET friend request
 */

export const GET_ALL_FRIENDS_REQUEST_LOADING =
  "GET_ALL_FRIENDS_REQUEST_LOADING";
export const GET_ALL_FRIENDS_REQUEST_SUCCESS =
  "GET_ALL_FRIENDS_REQUEST_SUCCESS";
export const GET_ALL_FRIENDS_REQUEST_ERROR = "GET_ALL_FRIENDS_REQUEST_ERROR";

/**
 * get friend friends
 */

export const GET_FRIEND_FRIENDS_LOADING = "GET_FRIEND_FRIENDS_LOADING";
export const GET_FRIEND_FRIENDS_SUCCESS = "GET_FRIEND_FRIENDS_SUCCESS";
export const GET_FRIEND_FRIENDS_ERROR = "GET_FRIEND_FRIENDS_ERROR";
