export const GET_ALL_FRIENDS_LOADING = "GET_ALL_FRIENDS_LOADING";
export const GET_ALL_FRIENDS_SUCCESS = "GET_ALL_FRIENDS_SUCCESS";
export const GET_ALL_FRIENDS_ERROR = "GET_ALL_FRIENDS_ERROR";

/**
 * GET friend request
 */

export const GET_ALL_FRIENDS_REQUEST_LOADING =
  "GET_ALL_FRIENDS_REQUEST_LOADING";
export const GET_ALL_FRIENDS_REQUEST_SUCCESS =
  "GET_ALL_FRIENDS_REQUEST_SUCCESS";
export const GET_ALL_FRIENDS_REQUEST_ERROR = "GET_ALL_FRIENDS_REQUEST_ERROR";

/**
 * get friend friends
 */

export const GET_FRIEND_FRIENDS_LOADING = "GET_FRIEND_FRIENDS_LOADING";
export const GET_FRIEND_FRIENDS_SUCCESS = "GET_FRIEND_FRIENDS_SUCCESS";
export const GET_FRIEND_FRIENDS_ERROR = "GET_FRIEND_FRIENDS_ERROR";

/**
 *  post
 * Friend Uid Request
 */
export const POST_FRIEND_UID_REQUEST_LOADING =
  "POST_FRIEND_UID_REQUEST_LOADING";
export const POST_FRIEND_UID_REQUEST_SUCCESS =
  "POST_FRIEND_UID_REQUEST_SUCCESS";
export const POST_FRIEND_UID_REQUEST_ERROR = "POST_FRIEND_UID_REQUEST_ERROR";

export const POST_FRIEND_UID_ACCEPT_REQUEST_LOADING =
  "POST_FRIEND_UID_REQUEST_LOADING";
export const POST_FRIEND_UID_ACCEPT_REQUEST_SUCCESS =
  "POST_FRIEND_UID_REQUEST_SUCCESS";
export const POST_FRIEND_UID_ACCEPT_REQUEST_ERROR =
  "POST_FRIEND_UID_REQUEST_ERROR";

export const POST_FRIEND_UID_ACCEPT_REQUEST_CANCEL_LOADING =
  "POST_FRIEND_UID_REQUEST_LOADING";
export const POST_FRIEND_UID_ACCEPT_REQUEST_CANCEL_SUCCESS =
  "POST_FRIEND_UID_REQUEST_SUCCESS";
export const POST_FRIEND_UID_ACCEPT_REQUEST_CANCEL_ERROR =
  "POST_FRIEND_UID_REQUEST_ERROR";

export const PUT_FRIEND_UID_UNFRIEND_LOADING =
  "PUT_FRIEND_UID_UNFRIEND_LOADING";
export const PUT_FRIEND_UID_UNFRIEND_SUCCESS =
  "PUT_FRIEND_UID_UNFRIEND_SUCCESS";
export const PUT_FRIEND_UID_UNFRIEND_ERROR = "PUT_FRIEND_UID_UNFRIEND_ERROR";

/**
 *  GET ALL FRIEND REQUEST
 *
 */

export const GET_ALL_FRIEND_REQUEST_LOADING = "GET_ALL_FRIEND_REQUEST_LOADING";
export const GET_ALL_FRIEND_REQUEST_SUCCESS = "GET_ALL_FRIEND_REQUEST_SUCCESS";
export const GET_ALL_FRIEND_REQUEST_ERROR = "GET_ALL_FRIEND_REQUEST_ERROR";
