/**
 * @GET /hub
 */
export const GET_ALL_HUB_LOADING = "GET_ALL_HUB_LOADING";
export const GET_ALL_HUB_SUCCESS = "GET_ALL_HUB_SUCCESS";
export const GET_ALL_HUB_ERROR = "GET_ALL_HUB_ERROR";

/**
 * @POST /hub
 */
export const POST_ALL_HUB_LOADING = "POST_ALL_HUB_LOADING";
export const POST_ALL_HUB_SUCCESS = "POST_ALL_HUB_SUCCESS";
export const POST_ALL_HUB_ERROR = "POST_ALL_HUB_ERROR";

/**
 * @POST /hub/filter
 */
export const GET_ALL_HUB_POST_FILTER_LOADING =
  "GET_ALL_HUB_POST_FILTER_LOADING";
export const GET_ALL_HUB_POST_FILTER_SUCCESS =
  "GET_ALL_HUB_POST_FILTER_SUCCESS";
export const GET_ALL_HUB_POST_FILTER_ERROR = "GET_ALL_HUB_POST_FILTER_ERROR";

/**
 *  @POST /hub/member
 */

export const POST_ALL_HUB_MEMBER_LOADING = "POST_ALL_HUB_MEMBER_LOADING";
export const POST_ALL_HUB_MEMBER_SUCCESS = "POST_ALL_HUB_MEMBER_SUCCESS";
export const POST_ALL_HUB_MEMBER_ERROR = "POST_ALL_HUB_MEMBER_ERROR";

/**
 *  @GET /hub/{HiD}
 */

export const GET_ALL_HUB_BY_ID_LOADING = "GET_ALL_HUB_BY_ID_LOADING";
export const GET_ALL_HUB_BY_ID_SUCCESS = "GET_ALL_HUB_BY_ID_SUCCESS";
export const GET_ALL_HUB_BY_ID_ERROR = "GET_ALL_HUB_BY_ID_ERROR";

/**
 *  @PUT /hub/{HiD}
 */

export const UPDATE_ALL_HUB_BY_ID_LOADING = "UPDATE_ALL_HUB_BY_ID_LOADING";
export const UPDATE_ALL_HUB_BY_ID_SUCCESS = "UPDATE_ALL_HUB_BY_ID_SUCCESS";
export const UPDATE_ALL_HUB_BY_ID_ERROR = "UPDATE_ALL_HUB_BY_ID_ERROR";

/**
 *  @PUT /hub/{HiD}/image
 */

export const UPDATE_IMAGE_HUB_BY_ID_LOADING = "UPDATE_IMAGE_HUB_BY_ID_LOADING";
export const UPDATE_IMAGE_HUB_BY_ID_SUCCESS = "UPDATE_IMAGE_HUB_BY_ID_SUCCESS";
export const UPDATE_IMAGE_HUB_BY_ID_ERROR = "UPDATE_IMAGE_HUB_BY_ID_ERROR";

/**
 *  @GET /hub/{HiD}/member
 */

export const GET_HUB_MEMBER_LOADING = "GET_HUB_MEMBER_LOADING";
export const GET_HUB_MEMBER_SUCCESS = "GET_HUB_MEMBER_SUCCESS";
export const GET_HUB_MEMBER_ERROR = "GET_HUB_MEMBER_ERROR";

/**
 *  @GET /hub/state
 */

export const GET_ALL_STATE_LOADING = "GET_ALL_STATE_LOADING";
export const GET_ALL_STATE_SUCCESS = "GET_ALL_STATE_SUCCESS";
export const GET_ALL_STATE_ERROR = "GET_ALL_STATE_ERROR";
