// getJewellerShop
export const GET_ALL_JEWELLERY_SHOP_LOADING = "GET_ALL_JEWELLERY_SHOP_LOADING";
export const GET_ALL_JEWELLERY_SHOP_SUCCESS = "GET_ALL_JEWELLERY_SHOP_SUCCESS";
export const GET_ALL_JEWELLERY_SHOP_ERROR = "GET_ALL_JEWELLERY_SHOP_ERROR";

// getJewellerWorker
export const GET_ALL_JEWELLERY_WORKER_LOADING =
  "GET_ALL_JEWELLERY_WORKER_LOADING";
export const GET_ALL_JEWELLERY_WORKER_SUCCESS =
  "GET_ALL_JEWELLERY_WORKER_SUCCESS";
export const GET_ALL_JEWELLERY_WORKER_ERROR = "GET_ALL_JEWELLERY_WORKER_ERROR";
