/**
 *
 */

export const GET_ALL_MATRIMONY_LOADING = "GET_ALL_MATRIMONY_LOADING";
export const GET_ALL_MATRIMONY_SUCCESS = "GET_ALL_MATRIMONY_SUCCESS";
export const GET_ALL_MATRIMONY_ERROR = "GET_ALL_MATRIMONY_ERROR";
export const GET_ALL_MATRIMONY_BRIDE_SUCCESS =
  "GET_ALL_MATRIMONY_BRIDE_SUCCESS";
export const GET_ALL_MATRIMONY_BRIDE_ERROR = "GET_ALL_MATRIMONY_BRIDE_ERROR";

export const MATRIMONY_CREATED_SUCCESS = "MATRIMONY_CREATED_SUCCESS";
export const MATRIMONY_CREATED_ERROR = "MATRIMONY_CREATED_ERROR";
export const MATRIMONY_CREATING = "MATRIMONY_CREATING";
/**
 * get by id
 */

export const GET_MATRIMONY_PROFILE_BY_ID_LOADING =
  "GET_MATRIMONY_PROFILE_BY_ID_LOADING";
export const GET_MATRIMONY_PROFILE_BY_ID_SUCCESS =
  "GET_MATRIMONY_PROFILE_BY_ID_SUCCESS";
export const GET_MATRIMONY_PROFILE_BY_ID_ERROR =
  "GET_MATRIMONY_PROFILE_BY_ID_ERROR";

export const GET_ALL_MATRIMONY_VENDOR_LOADING =
  "GET_ALL_MATRIMONY_VENDOR_LOADING";
export const GET_ALL_MATRIMONY_VENDOR_SUCCESS =
  "GET_ALL_MATRIMONY_VENDOR_SUCCESS";
export const GET_ALL_MATRIMONY_VENDOR_ERROR = "GET_ALL_MATRIMONY_VENDOR_ERROR";

export const GET_ALL_MATRIMONY_VENDOR_DETAIL_LOADING =
  "GET_ALL_MATRIMONY_VENDOR_DETAIL_LOADING";
export const GET_ALL_MATRIMONY_VENDOR_DETAIL_SUCCESS =
  "GET_ALL_MATRIMONY_VENDOR_DETAIL_SUCCESS";
export const GET_ALL_MATRIMONY_VENDOR_DETAIL_ERROR =
  "GET_ALL_MATRIMONY_VENDOR_DETAIL_ERROR";

export const POST_MATRIMONY_VENDOR_LOADING = "POST_MATRIMONY_VENDOR_LOADING";
export const POST_MATRIMONY_VENDOR_LOADING_SUCCESS =
  "POST_MATRIMONY_VENDOR_LOADING_SUCCESS";
export const POST_MATRIMONY_VENDOR_LOADING_ERROR =
  "POST_MATRIMONY_VENDOR_LOADING_ERROR";
