/**
 *
 */

export const GET_ALL_MATRIMONY_LOADING = "GET_ALL_MATRIMONY_LOADING";
export const GET_ALL_MATRIMONY_SUCCESS = "GET_ALL_MATRIMONY_SUCCESS";
export const GET_ALL_MATRIMONY_ERROR = "GET_ALL_MATRIMONY_ERROR";

export const MATRIMONY_CREATED_SUCCESS = "MATRIMONY_CREATED_SUCCESS";
export const MATRIMONY_CREATED_ERROR = "MATRIMONY_CREATED_ERROR";
