export const GET_ALL_NOTIFICATION_LOADING = "GET_ALL_NOTIFICATION_LOADING";
export const GET_ALL_NOTIFICATION_SUCCESS = "GET_ALL_NOTIFICATION_SUCCESS";
export const GET_ALL_NOTIFICATION_ERROR = "GET_ALL_NOTIFICATION_ERROR";
