export const USER_DATA_LOADING = "USER_DATA_LOADING";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const USER_DATA_ERROR = "USER_DATA_ERROR";

/**
 * Edit Profile
 */

export const USER_EDIT_PROFILE_SUCCESS = "USER_EDIT_PROFILE_SUCCESS";
export const USER_EDIT_PROFILE_ERROR = "USER_EDIT_PROFILE_ERROR";

/**
 * User Profile Picture
 */

export const USER_PROFILE_PICTURE_SUCCESS = "USER_PROFILE_PICTURE_SUCCESS";
export const USER_PROFILE_PICTURE_ERROR = "USER_PROFILE_PICTURE_ERROR";

export const UPDATE_COVER_IMAGE_SUCCESS = "UPDATE_COVER_IMAGE_SUCCESS";
export const UPDATE_COVER_IMAGE_ERROR = "UPDATE_COVER_IMAGE_ERROR";

export const GET_USER_DETAIL_BY_ID_LOADING = "GET_USER_DETAIL_BY_ID_LOADING";
export const GET_USER_DETAIL_BY_ID_SUCCESS = "GET_USER_DETAIL_BY_ID_SUCCESS";
export const GET_USER_DETAIL_BY_ID_ERROR = "GET_USER_DETAIL_BY_ID_ERROR";

/**
 * all Member
 */

export const GET_ALL_USER_LOADING = "GET_ALL_USER_LOADING";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_ERROR = "GET_ALL_USER_ERROR";
