export const USER_DATA_LOADING = "USER_DATA_LOADING";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const USER_DATA_ERROR = "USER_DATA_ERROR";

/**
 * Edit Profile
 */

export const USER_EDIT_PROFILE_SUCCESS = "USER_EDIT_PROFILE_SUCCESS";
export const USER_EDIT_PROFILE_ERROR = "USER_EDIT_PROFILE_ERROR";
