export type createMatrimonyProps = {
  image: string;
  firstName: string;
  lastName: string;
  email: string;
  phoneNumber: string;
  companyName: string;
  designation: string;
  education: string;
  livesIn: string;
  about: string;
  interest: string;
  gender: string;
};
export type horizontalCardDataType = {
  about: string;
  companyName: string;
  creationDate: number;
  designation: string;
  education: string;
  email: string;
  firstName: string;
  gender: string;
  images: any;
  interest: string;
  lastName: string;
  livesIn: string;
  pId: number;
  phoneNumber: string;
  updatedDate: number;
  btn: string;
};
